"""Planner and managed-file detection tests (PRD §12.1, §16.2, §20.4)."""

from __future__ import annotations

from pathlib import Path

from wfctl.loader import load_workflows
from wfctl.plan import (
    Action,
    build_plan,
    discover_managed_units,
    is_managed_unit_file,
)
from wfctl.render import render_service


def _managed_unit_text() -> str:
    return (
        "# Generated by wfctl. Do not edit directly.\n"
        "# Managed-By: wfctl\n"
        "# Workflow-Id: x\n[Unit]\nDescription=x\n"
    )


def test_is_managed_requires_name_and_marker(tmp_path: Path):
    managed = tmp_path / "wfctl-x.service"
    managed.write_text(_managed_unit_text())
    assert is_managed_unit_file(managed)

    # right marker, wrong name
    wrong_name = tmp_path / "x.service"
    wrong_name.write_text(_managed_unit_text())
    assert not is_managed_unit_file(wrong_name)

    # right name, no marker
    no_marker = tmp_path / "wfctl-y.service"
    no_marker.write_text("[Unit]\nDescription=hand written\n")
    assert not is_managed_unit_file(no_marker)


def test_discover_managed_units_ignores_unmanaged(tmp_path: Path):
    (tmp_path / "wfctl-a.service").write_text(_managed_unit_text())
    (tmp_path / "wfctl-a.timer").write_text(_managed_unit_text())
    (tmp_path / "other.service").write_text("[Unit]\n")
    (tmp_path / "wfctl-evil.service").write_text("[Unit]\nno marker\n")
    found = discover_managed_units(tmp_path)
    assert set(found) == {"wfctl-a.service", "wfctl-a.timer"}


def test_plan_create_for_scheduled_and_manual(workflows_dir: Path, tmp_path: Path):
    unit_dir = tmp_path / "units"
    unit_dir.mkdir()
    workflows = load_workflows(workflows_dir)
    plan = build_plan(workflows, unit_dir)
    actions = {(i.unit_name, i.action) for i in plan.items}
    # daily-news is scheduled -> service + timer; manual-job -> service only
    assert ("wfctl-daily-news.service", Action.CREATE) in actions
    assert ("wfctl-daily-news.timer", Action.CREATE) in actions
    assert ("wfctl-manual-job.service", Action.CREATE) in actions
    assert "wfctl-manual-job.timer" not in {n for n, _ in actions}


def test_plan_unchanged_then_update(workflows_dir: Path, tmp_path: Path):
    unit_dir = tmp_path / "units"
    unit_dir.mkdir()
    workflows = load_workflows(workflows_dir)

    # Pre-write the exact desired service for daily-news.
    daily = next(w for w in workflows if w.id == "daily-news")
    (unit_dir / "wfctl-daily-news.service").write_text(render_service(daily))

    plan = build_plan(workflows, unit_dir)
    by_name = {i.unit_name: i.action for i in plan.items}
    assert by_name["wfctl-daily-news.service"] is Action.UNCHANGED
    assert by_name["wfctl-daily-news.timer"] is Action.CREATE

    # Now mutate the on-disk file -> UPDATE.
    (unit_dir / "wfctl-daily-news.service").write_text("# Managed-By: wfctl\nchanged\n")
    plan2 = build_plan(workflows, unit_dir)
    assert {i.unit_name: i.action for i in plan2.items}["wfctl-daily-news.service"] is Action.UPDATE


def test_prune_only_when_requested(workflows_dir: Path, tmp_path: Path):
    unit_dir = tmp_path / "units"
    unit_dir.mkdir()
    # An orphaned managed unit with no backing workflow.
    orphan = unit_dir / "wfctl-orphan.service"
    orphan.write_text(_managed_unit_text())
    workflows = load_workflows(workflows_dir)

    plan = build_plan(workflows, unit_dir, prune=False)
    assert not any(i.action is Action.DELETE for i in plan.items)

    plan_pruned = build_plan(workflows, unit_dir, prune=True)
    deletes = [i.unit_name for i in plan_pruned.items if i.action is Action.DELETE]
    assert deletes == ["wfctl-orphan.service"]
