"""Render workflow models into systemd unit text (PRD §10–11, §15).

Rendering is done with explicit string building rather than a template engine
(PRD §26): the output is small, fully under our control, and easier to audit
for injection safety. Line ordering matches the PRD §11 golden example so the
generated units are stable and diffable.
"""

from __future__ import annotations

from .loader import LoadedWorkflow
from .models import (
    ExecConfig,
    ExecMode,
    RestartPolicy,
    SecurityConfig,
    SecurityProfile,
    WorkflowDefinition,
)

MANAGED_BY_MARKER = "Managed-By: wfctl"
DEFAULT_UV_BINARY = "uv"

# systemd hardening directives by profile. Each profile is a superset of the
# previous one (PRD §9.8). Rendered in this exact order.
_BASIC = [
    ("NoNewPrivileges", "true"),
    ("PrivateTmp", "true"),
    ("RestrictSUIDSGID", "true"),
]
_READONLY_HOME = _BASIC + [("ProtectHome", "read-only")]
_STRICT = _READONLY_HOME + [
    ("ProtectSystem", "strict"),
    ("PrivateDevices", "true"),
    ("LockPersonality", "true"),
]
_NETWORKLESS = _STRICT + [("PrivateNetwork", "true")]

_SECURITY_DIRECTIVES: dict[SecurityProfile, list[tuple[str, str]]] = {
    SecurityProfile.NONE: [],
    SecurityProfile.BASIC: _BASIC,
    SecurityProfile.READONLY_HOME: _READONLY_HOME,
    SecurityProfile.STRICT: _STRICT,
    SecurityProfile.NETWORKLESS: _NETWORKLESS,
}


def _needs_quoting(arg: str) -> bool:
    if arg == "":
        return True
    return any(ch.isspace() or ch in '"\\' for ch in arg)


def quote_exec_arg(arg: str) -> str:
    """Quote a single ExecStart argument for systemd's command-line parser.

    systemd splits ExecStart on whitespace and supports double-quoted tokens
    with C-style backslash escapes. We only quote when necessary so simple
    commands render cleanly (and match the golden example).
    """
    if not _needs_quoting(arg):
        return arg
    escaped = arg.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_exec_start(exec_cfg: ExecConfig) -> str:
    """Build the ExecStart value for a workflow's exec configuration."""
    uv = exec_cfg.uv_binary or DEFAULT_UV_BINARY

    if exec_cfg.mode is ExecMode.UV_RUN:
        parts = [uv, "run"]
        if exec_cfg.python:
            parts += ["--python", exec_cfg.python]
        if exec_cfg.frozen:
            parts.append("--frozen")
        if exec_cfg.no_sync:
            parts.append("--no-sync")
        parts.append("--")
        parts += [quote_exec_arg(a) for a in (exec_cfg.command or [])]
        return " ".join(parts)

    if exec_cfg.mode is ExecMode.UV_SCRIPT:
        # script is validated absolute; quote defensively in case of spaces.
        return f"{uv} run --script {quote_exec_arg(exec_cfg.script or '')}"

    # mode == command: render the argv directly, no shell wrapper (PRD §16.3).
    return " ".join(quote_exec_arg(a) for a in (exec_cfg.command or []))


def _managed_header(wf: LoadedWorkflow) -> list[str]:
    return [
        "# Generated by wfctl. Do not edit directly.",
        f"# {MANAGED_BY_MARKER}",
        f"# Workflow-Id: {wf.id}",
        f"# Source-Path: {wf.source_path}",
        f"# Source-SHA256: {wf.source_sha256}",
    ]


def _bool(value: bool) -> str:
    return "true" if value else "false"


def render_service(wf: LoadedWorkflow) -> str:
    """Render the ``wfctl-<id>.service`` unit text."""
    d: WorkflowDefinition = wf.definition
    lines: list[str] = _managed_header(wf)

    # [Unit]
    lines.append("[Unit]")
    lines.append(f"Description=Workflow: {d.description}")
    lines.append(f"Documentation=file:{wf.source_path}")
    if d.restart:
        if d.restart.start_limit_interval_sec is not None:
            lines.append(f"StartLimitIntervalSec={d.restart.start_limit_interval_sec}")
        if d.restart.start_limit_burst is not None:
            lines.append(f"StartLimitBurst={d.restart.start_limit_burst}")

    # [Service]
    lines.append("[Service]")
    lines.append("Type=oneshot")
    if d.exec.working_directory:
        lines.append(f"WorkingDirectory={d.exec.working_directory}")
    lines.append(f"ExecStart={render_exec_start(d.exec)}")

    if d.environment:
        for name, value in d.environment.variables.items():
            lines.append(f"Environment={_render_env_assignment(name, value)}")
        for env_file in d.environment.files:
            lines.append(f"EnvironmentFile={env_file}")

    if d.timeout_sec is not None:
        lines.append(f"TimeoutStartSec={d.timeout_sec}")

    if d.restart and d.restart.policy is not RestartPolicy.NO:
        lines.append(f"Restart={d.restart.policy.value}")
        if d.restart.restart_sec is not None:
            lines.append(f"RestartSec={d.restart.restart_sec}")

    lines.extend(_render_security(d.security))

    if d.resources:
        if d.resources.memory_max is not None:
            lines.append(f"MemoryMax={d.resources.memory_max}")
        if d.resources.cpu_quota is not None:
            lines.append(f"CPUQuota={d.resources.cpu_quota}")
        if d.resources.tasks_max is not None:
            lines.append(f"TasksMax={d.resources.tasks_max}")

    lines.append(f"SyslogIdentifier=wfctl-{d.id}")

    return "\n".join(lines) + "\n"


def _render_env_assignment(name: str, value: str) -> str:
    """Render ``KEY=VALUE`` for Environment=, quoting values with whitespace.

    Newlines are already rejected at validation time.
    """
    if value == "" or any(ch.isspace() for ch in value) or '"' in value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{name}={escaped}"'
    return f"{name}={value}"


def _render_security(security: SecurityConfig | None) -> list[str]:
    if security is None:
        return []
    lines = [f"{key}={val}" for key, val in _SECURITY_DIRECTIVES[security.profile]]
    for path in security.read_write_paths:
        lines.append(f"ReadWritePaths={path}")
    return lines


def render_timer(wf: LoadedWorkflow) -> str:
    """Render the ``wfctl-<id>.timer`` unit text. Caller ensures a schedule exists."""
    d = wf.definition
    assert d.schedule is not None  # guarded by callers / has_timer
    sched = d.schedule

    lines: list[str] = _managed_header(wf)
    lines.append("[Unit]")
    lines.append(f"Description=Timer for workflow: {d.id}")
    lines.append("[Timer]")
    for expr in sched.calendar_expressions:
        lines.append(f"OnCalendar={expr}")
    if sched.persistent is not None:
        lines.append(f"Persistent={_bool(sched.persistent)}")
    if sched.randomized_delay_sec is not None:
        lines.append(f"RandomizedDelaySec={sched.randomized_delay_sec}")
    lines.append(f"Unit=wfctl-{d.id}.service")
    lines.append("[Install]")
    lines.append("WantedBy=timers.target")

    return "\n".join(lines) + "\n"
